#!/bin/bash

# Read the rows into an array of lines.
lines=()
n=0
while read -r line; do

 if [ $n == 0 ]; then
   if [ "${line:0:1}" == "+" ]; then
     ruler=$line
   fi
 fi

 if [ "${line:0:1}" != "+" ]; then
    lines+=( "$line" )
    (( n++ ))
 fi
done

# Determine the number and length of each field/column.
x=${ruler/#+/}
x=${ruler/%+/}
IFS='+'
read -ra lengths <<< "$x"

rulerDelims=${ruler//[^+]/}
m=${#rulerDelims}

widths=()
for fromRow in "${lines[@]}" ; do
  colWidth=0
  xj=2
  xm=${#lengths[1]}
  k=2
  for ((j=2;j<m;j++)) do
    x=${fromRow:$xj:$xm-1}
    x="   $x"
    shopt -s extglob
    x=${x/#*( )/}
    x=${x/%*( )/}
    shopt -u extglob
    fieldLen=${#x}
    if [ $fieldLen -gt $colWidth ]; then
      colWidth=$fieldLen
    fi
    xj=$(( xj+xm+1 ))
    xm=${#lengths[$k]}
    (( k++ ))
  done
# if [ $colWidth -gt 16 ]; then
#   colWidth=16
# fi
  widths+=( "$colWidth" )
done

# Output the columns in rows.
xi=2
xn=${#lengths[1]}
for ((i=2;i<m;i++)) do

  toRow=""
  j=0
  for fromRow in "${lines[@]}" ; do
    x=${fromRow:$xi:$xn-1}
    x="   $x"
    shopt -s extglob
    x=${x/#*( )/}
    x=${x/%*( )/}
    shopt -u extglob
    field=${x}

    colWidth=${widths[$j]}

    printf -v colPad %${colWidth}s

    field=$colPad$field
    fieldWidth=${#field}
    field=${field:$fieldWidth-$colWidth:$colWidth}
    toRow="$toRow|$field"
    (( j++ ))
  done

  toRow="$toRow|"
  echo "$toRow"
  xi=$(( xi+xn+1 ))
  xn=${#lengths[$i]}
done

